# Define strings and paths for webtest
#
# Note that the getProperty(...) method replaces placeholders
# see Util.propertyReplace for a description
#
# Note that intellij at least does not recognize that this is taking
# place so flags properties used solely for placeholders as unused.

super = common-webtest.properties
