# Define common strings and paths for bedework webtest
#
# Note that the getProperty(...) method replaces placeholders
# see Util.propertyReplace for a description
#
# Note that intellij at least does not recognize that this is taking
# place so flags properties used solely for placeholders as unused.

# Set this to define a parent property file
# These are loaded in reverse order so that the highest parent is
# loaded first and the children override the parent.
# the chain terminates when the property is empty or unchanged
super =

# -------------------- Reserved properties -------------------
# These are properties that are set by the testsuite and may
# be embedded in property values.

# Used for messages that only differ by client name, e.g. login
# Set at start of tests. Use the localized properties shown below,
# e.g. publicClientName etc.
clientName =

groupName =

# To identify reason for login
loginPurpose =

member =

time =

# Current user
user =

# To identify the test and associated events
uuid =

# Parameters to xpath
xpathPar1 =
xpathPar2 =

# ------------------ End reserved properties -----------------

driverType = FIREFOX

# -------------------- General properties -------------------
defaultHost = http://localhost:8080

# Logout string - found in the URL
logoutText = logout=true

bedeworkLogo = https://github.com/Bedework/bw-calendar-xsl/raw/master/bw-calendar-xsl-calrsrc-MainCampus/src/main/webapp/themes/currentTheme/images/bedeworkLogo.png
bedeworkLogoThumb = https://github.com/Bedework/bw-calendar-xsl/raw/master/bw-calendar-xsl-calrsrc-MainCampus/src/main/webapp/themes/currentTheme/images/bedework.png

# -------------------- Localized properties -----------------
# This group of properties are affected by localization.
# If you want to test a localized version of bedework you
# need to change these to match
#
# -------- Admin client
adminClientName = admin

adminAddedEventText = added
adminDeletedEventText = deleted

adminDeleteEventText = Delete Event

adminDeleteEventConfirmText = Yes: Delete Event

adminEventInfoTitle = Event Information
adminManageEventsTitle = Manage Events

# Error messages we expect to see
adminErrorUpdateEventTopicalArea = please supply at least one topical area
adminErrorUpdateEventNoTitle = please supply a title
adminErrorUpdateEventNoDescription = please supply a description
adminErrorUpdateEventNoLocation = please supply a location
adminErrorUpdateEventNoContact = please supply a contact

#-------------- event reg
eventregClientName = event registration

eventregDeletedEventText = deleted

eventregEventDescription = ${eventregTitlePrefix} \
  eventreg test description

eventregTitlePrefix = Bedework Eventreg: 

eventregEventTitle = ${eventregTitlePrefix} EventregTest - \
  ${uuid}

#-------------- personal
personalClientName = personal

personalDeleteSubscriptionConfirmText = Yes: Delete Calendar!

personalDeleteSubscriptionText = Delete Subscription

personalDeletedSubCalText = Deleted

personalManageCalTitle = Manage Calendars & Subscriptions

personalSubmissionConcertsName = Concerts

#-------------- public
publicClientName = public

publicEventAddDescription = Bedework public event \
  add event test description

publicEventApprovalDescription = Bedework public event \
  approval test description

publicEventTitlePrefix = Bedework TestSuite: 

publicEventTitle = ${publicEventTitlePrefix} CreatePubEventsTest - \
  ${uuid}

#-------------- submissions
submissionsClientName = submissions

submissionsEventTitlePrefix = Bedework submission: 
submissionsEventDescription = bedework submission test description 

submissionsErrors = Errors on event submission: 

# ---- optionally localizable-----------
# Allows for localization - not necessary. These are strings output
# by the tests

# Login purposes
adminLoginCheckPendingPurpose = check pending queue
adminLoginAddPublicEventPurpose = add public event
adminLoginRemovePublicEventPurpose = remove the public event
adminLoginCleanupPurpose = Clean up for admin
adminLoginSetupApproverGroupsPurpose = set up approver user in 2 groups
adminLoginSetupApproverPurpose = set up approver user
adminLoginSetupNonapproverPurpose = set up non-approver user
adminLoginApproverCheckTabsPurpose = as approver to check tabs
adminLoginApproverApproveEventPurpose = as approver to approve event
adminLoginNonapproverCheckTabsPurpose = as non-approver to check tabs
adminLoginNonapproverAddEventPurpose = as non-approver to add event

eventregLoginAddEventPurpose = add an event and register a user

personalAddSubscriptionPurpose = Add a public event subscription
submissionsLoginAddEventPurpose = submit a public event that is accepted

# Assertions
assertionFooterMustContain = Footer must contain correct text: 

assertionAdminApproverVisibleTabs = Should not see user and system tabs

assertionAdminErrorNotNoContact = Should not have 'no contact' error: 

assertionAdminErrorNoContact = Error should be shown for 'no contact': 

assertionAdminErrorNoLocation = Error should be shown for 'no location': 

assertionAdminErrorNoTopicalArea = Error should be shown for no topical area: 

assertionAdminGroupexists = Admin group ${groupName} must exist

assertionAdminMustHaveDeleted = Must have '${adminDeletedEventText}' message

assertionAdminMustHaveAdded = Must have '${adminAddedEventText}' message

assertionAdminNonappproverVisibleTabs = Should see home, add event and approval q tabs only

assertionEventregFieldsMissing = Event registration fields missing \
  for event ${uuid}

assertionEventregMustHaveDeleted = Must have '${eventregDeletedEventText}' message

# Any client
msgCommonAboutToLogin = About to log in to the ${clientName} \
  client as user "${user} for ${loginPurpose}

msgCommonLoggedIn = Logged into the ${clientName} client as user "${user}"

# ------------ Admin client
msgAdminOnEventInfoPage = On ${adminEventInfoTitle} page
msgAdminOnManageEventsPage = On ${adminManageEventsTitle} page

msgAdminTryNonapproverLogin = Try login as non-approver \
  ${nonApproverUser}

msgAboutToSubscribeToConcerts = About to subscribe to \
  ${personalSubmissionConcertsName}

msgDeleteExistingSubscription = Delete existing subscription

msgEventFound = Event "${uuid}" found.

msgMustHaveDeleted = Must have 'deleted' message

msgEventPublishedCheckingPublic = \
  Event is published. Now checking event in public web client.

msgEventregLogin = Log in to register for event as ${eventregUser}

msgEventregSuccess = Successfully registered for event ${uuid}

msgPersonalOnManageCalPage = On ${personalManageCalTitle} page

msgPersonalLoggedIn = Logged into personal client as user "${user}"
msgPersonalLoginPurpose = About to log in to personal client as user "${user} for ${loginPurpose}

msgPublicSubscriptionAdded = Public subscription to \
  ${personalSubmissionConcertsName} added.

msgPublicSubscriptionClicked = Public subscription \
  ${personalSubmissionConcertsName} clicked.

msgSubmissionLoggedIn = Logged into submissions client as user "${user}"
msgSubmissionLoginPurpose = About to log in to submissions client as user "${user} for ${loginPurpose}
 # ----------- End of optionally localizable

# ---------------------------------------------------
# The following properties are divided into groups by application.
# The intent is that none of these need localization changes.
# Any values that contain locale sensitive text should include that
# via a placeholder referring to a property in the localized group
# at the start
# --------------------- common properties -------------------

commonLogoutButton = \
  //a[@id=\"bwLogoutButton\" and \
  contains(@href, '${logoutText}')]

commonExpectedTime = Time should be at "${time}":

commonFooterLinkHrefPath = \
  //footer/a[contains(@href,'bedework.github.io')]

# --------------------- Admin properties -------------------

adminHost = ${defaultHost}
adminHome = ${adminHost}/caladmin

# Approver user - not superuser
approverUser = vbede
approverPrincipal = /principals/users/vbede
approverUserPw = bedework
approverUserGroupName = calsuite-MainCampus

nonApproverUser = caladmin
nonApproverPrincipal = /principals/users/caladmin
nonApproverUserPw = bedework
nonApproverUserGroupName = nonapprovers-MainCampus
nonApproverGroupParentName = calsuite-MainCampus

# Approver user in 2 groups above
approverUser2Groups = bfranklin
approverPrincipal2Groups = /principals/users/bfranklin
approverUser2GroupsPw = bedework

adminSuperUser = admin
adminSuperUserPw = bedework

adminApproveButtonInRow = \
  //button[@class="approve"]

adminAuthUserUpdateLink = authuser/initUpdate.do

adminClaimSubmittedEventPath = \
  //form[@id='bwEventForm']\
  //input[@id='claimPendingEvent']

adminDeleteEventLink = //input[@value='${adminDeleteEventText}']
adminDeleteEventConfirm = //input[@value='${adminDeleteEventConfirmText}']

# Values for added event
adminEventTopicalArea1 = /user/agrp_calsuite-MainCampus/Arts/Concerts
adminEventTopicalArea1Xpath = //input[@name='alias' and @value='${adminEventTopicalArea1}']

adminEventLink = https://www.apereo.org/programs/software/bedework
adminEventByUUID = \
  //table[@id='commonListTable']\
  /tbody/tr/td\
  /a[contains(text(),'${uuid}')]

adminGroupManageLink = admingroup/initUpdate.do

adminGroupManageMembersPagePath = \
  ${adminHome}/admingroup/fetchForUpdateMembers.do\
  ?b=de&adminGroupName=${groupName}

adminSelectInContactSearch = \
  //div[@id="bwContactSearchResults"]/ul/li[1]

adminSelectInLocSearch = \
  //div[@id="bwLocationSearchResults"]/ul/li[1]

adminTabHomePath = \
  //ul[@id='bwAdminMenu']/li\
  /a[contains(@href,'showHome.rdo')]

adminTabAddEventPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'initAddEvent.do')]

adminTabApprovalqPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'initApprovalQueueTab.do')]

adminTabManageEventsPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'initUpdateEvent.do')]

adminTabSuggestionqPath = //ul[@id="bwAdminMenu"]/li/a[text()="Suggestion Queue"]

adminTabPendingqPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'initPendingTab.do')]

adminTabContactsPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'showContactsTab.rdo')]

adminTabLocationsPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'showLocationsTab.rdo')]

adminTabCategoriesPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'showCategoriesTab.rdo')]

adminTabCalendarSuitePath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'showCalsuiteTab.rdo')]

adminTabUsersPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'showUsersTab.rdo')]

adminTabSystemPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'showSystemTab.rdo')]

adminTabhelpPath = \
  //ul[@id="bwAdminMenu"]/li\
  /a[contains(@href,'showHelp.rdo')]

# --------------------- Public properties -------------------

publicHost = http://localhost:8080
publicHome = ${publicHost}/cal/setup.do

publicEventByUUID = \
  //div[@id='listEvents']\
  //div[@class='bwSummary']\
  /a[contains(text(),'${uuid}')]

publicEventTime = //div[@class='eventWhen']//span[@class='time']

# --------------------- Personal properties -------------------

personalHost = ${defaultHost}
personalHome = ${personalHost}/ucal

personalUser = vbede
personalPw = bedework

# Sidebar nav path to submission
personalNavXpathSubmissionConcerts = //td[@id='sideBar']\
  /ul[@class='calendarTree']\
  //li[@class='alias']\
  /a[contains(text(), '${submissionConcertsName}')]

personalXpathManageSubmissionConcerts = //table[@id='calendarTable']\
  //ul[@class='calendarTree']\
  //li[@class='alias']\
  /a[contains(text(), '${submissionConcertsName}')]";

# manage calendars page
personalManageCalendarsLink = //a[@class='calManageLink']

# Path and value of text
personalManageCalendarsValidationPath = //table[@class='withNotices']\
  /tbody/tr/td[@id='bodyContent']/h2

personalManageCalendarsValidationValue = ${personalManageCalTitle}

personalManageCalendarsSelectSubscriptionConcerts = \
  //ul[@id='publicSubscriptionTree']\
  //li[@class='alias']\
  /a[text()='${submissionConcertsName}']

personalDeleteSubscriptionPath = \
  //input[@value='${personalDeleteSubscriptionText}']

personalDeleteSubscriptionConfirmPath = \
  //input[@value='${personalDeleteSubscriptionConfirmText}']

personalSubFindPublicEvent = //table[@id='monthCalendarTable']\
  //a[contains(text(), '${publicEventTitlePrefix}')]

# --------------------- Eventreg properties ------------------

eventregUser = ggalilei
eventregPw = bedework

# ------------------- Submission properties -------------------

submissionsHost = ${defaultHost}
submissionsHome = ${submissionsHost}/eventsubmit

submissionsUser = ggalilei
submissionsPw = bedework

submissionsAddEventPath = \
  //ul[@id='menuTabs']/li\
  /a[contains(@href, 'initEvent.do')]

submissionsEventByUUID = \
  //table[@id='commonListTable']\
  /tbody/tr/td\
  /a[contains(text(),'${uuid}')]

submissionsEventTitle = ${submissionsEventTitlePrefix} - ${uuid} 

submitEventTopicalArea1 = /user/agrp_calsuite-MainCampus/Arts/Concerts
submitEventTopicalArea1Xpath = //input[@name='alias' and @value='${submitEventTopicalArea1}']

submissionsPendingTabPath = \
  //ul[@id='menuTabs']/li\
  /a[contains(@href, 'initPendingEvents.do')]
